RequestCategory.create("name"=>"Computer Assistance")
RequestCategory.create("name"=>"Directions (Building)")
RequestCategory.create("name"=>"Directions (On Campus)")
RequestCategory.create("name"=>"Directions (External)")
RequestCategory.create("name"=>"Directory Search/Info.")
RequestCategory.create("name"=>"Events or Event Info.")
RequestCategory.create("name"=>"Flyer Approval")
RequestCategory.create("name"=>"Hours of Operation")
RequestCategory.create("name"=>"Lost & Found")
RequestCategory.create("name"=>"Radio for Assistance")
RequestCategory.create("name"=>"Referral to Dept./Svc.")
RequestCategory.create("name"=>"Supplies Request")
RequestCategory.create("name"=>"Classes/Academic Info.")
PatronType.create("name"=>"Phone Calls")
PatronType.create("name"=>"Walk Ups")
PatronType.create("name"=>"Switchboard Back-Up")
Timespan.create("name"=>"7:00 a.m. - 7:30 a.m.", "starttime"=>"7:00 a.m.", "endtime"=>"7:30 a.m.")
Timespan.create("name"=>"8:00 a.m. - 8:30 a.m.", "starttime"=>"8:00 a.m.", "endtime"=>"8:30 a.m.")
Timespan.create("name"=>"7:30 a.m. - 8:00 a.m.", "starttime"=>"7:30 a.m.", "endtime"=>"8:00 a.m.")
Timespan.create("name"=>"8:00 a.m. - 8:30 a.m.", "starttime"=>"8:00 a.m.", "endtime"=>"8:30 a.m.")
Timespan.create("name"=>"9:00 a.m. - 9:30 a.m.", "starttime"=>"9:00 a.m.", "endtime"=>"9:30 a.m.")
Timespan.create("name"=>"8:30 a.m. - 9:00 a.m.", "starttime"=>"8:30 a.m.", "endtime"=>"9:00 a.m.")
Timespan.create("name"=>"9:30 a.m. - 10:00 a.m.", "starttime"=>"9:30 a.m.", "endtime"=>"10:00 a.m.")
Timespan.create("name"=>"10:00 a.m. - 10:30 a.m.", "starttime"=>"10:00 a.m.", "endtime"=>"10:30 a.m.")
Timespan.create("name"=>"10:30 a.m. - 11:00 a.m.", "starttime"=>"10:30 a.m.", "endtime"=>"11:00 a.m.")
Timespan.create("name"=>"11:00 a.m. - 11:30 a.m.", "starttime"=>"11:00 a.m.", "endtime"=>"11:30 a.m.")
Timespan.create("name"=>"12:00 p.m. - 12:30 p.m.", "starttime"=>"12:00 p.m.", "endtime"=>"12:30 p.m.")
Timespan.create("name"=>"12:30 p.m. - 1:00 p.m.", "starttime"=>"12:30 p.m.", "endtime"=>"1:00 p.m.")
Timespan.create("name"=>"1:00 p.m. - 1:30 p.m.", "starttime"=>"1:00 p.m.", "endtime"=>"1:30 p.m.")
Timespan.create("name"=>"1:30 p.m. - 2:00 p.m.", "starttime"=>"1:30 p.m.", "endtime"=>"2:00 p.m.")
Timespan.create("name"=>"11:30 a.m. - 12:00 p.m.", "starttime"=>"11:30 a.m.", "endtime"=>"12:00 p.m.")
